FROM golang:1.24-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

#Install build essentials
# RUN apk add --no-cache gcc musl-dev
RUN apk --no-cache add ca-certificates tzdata

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Use air for live reloading in development
# CMD [ "air", "-c", ".air.toml" ]
