services:
  app-stage:
    container_name: zolaris-go-backend-stage
    image: 864981729345.dkr.ecr.ap-south-1.amazonaws.com/zolaris-go-app:staging

    ports:
      - "80:8080"
    environment:
      - EXTERNAL_URL=http://3.110.190.71
      - ENVIRONMENT=staging
      - PORT=8080
      - DEVICE_TABLE_NAME=machine_table
      - DATA_TABLE_NAME=machine_data_table
      - USER_TABLE_NAME=user_table
      - IOT_POLICY_NAME=iot_p
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
