services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "8080:8080"
    environment:
        - ENVIRONMENT=development
        - PORT=8080
        - DEVICE_TABLE_NAME=machine_table
        - DATA_TABLE_NAME=machine_data_table
        - USER_TABLE_NAME=user_table
        - IOT_POLICY_NAME=iot_p
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
        - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
    volumes:
      - ./:/app
    restart: unless-stopped
    command: air
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
