// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Register a new IoT device for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device Management"
                ],
                "summary": "Add a new device",
                "parameters": [
                    {
                        "description": "Device information",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Device added successfully",
                        "schema": {
                            "$ref": "#/definitions/gin.Response"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/device/attach-policy": {
            "post": {
                "description": "Attach an AWS IoT policy to a Cognito identity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy Management"
                ],
                "summary": "Attach IoT policy",
                "parameters": [
                    {
                        "description": "Identity information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AttachIotPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "IoT policy attached successfully",
                        "schema": {
                            "$ref": "#/definitions/gin.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to attach IoT policy",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/device/sensor-data": {
            "post": {
                "description": "Retrieve sensor data for a specific device with time filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device Data"
                ],
                "summary": "Get device sensor data",
                "parameters": [
                    {
                        "description": "Request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetDeviceSensorDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sensor data for the device",
                        "schema": {
                            "$ref": "#/definitions/models.GetDeviceSensorDataResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/devices": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all devices registered to the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device Management"
                ],
                "summary": "List user devices",
                "responses": {
                    "200": {
                        "description": "List of user devices",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DeviceResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gin.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.ErrorResponse": {
            "description": "Standard API error response format",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Something went wrong"
                },
                "status": {
                    "description": "Always false for errors",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "gin.Response": {
            "description": "Standard API success response format",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Optional data payload"
                },
                "message": {
                    "description": "Optional success message",
                    "type": "string",
                    "example": "Operation successful"
                },
                "status": {
                    "description": "Indicates success status",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.AddDeviceRequest": {
            "type": "object",
            "required": [
                "deviceId",
                "deviceName"
            ],
            "properties": {
                "deviceId": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "deviceName": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "models.AttachIotPolicyRequest": {
            "type": "object",
            "required": [
                "identityId"
            ],
            "properties": {
                "identityId": {
                    "type": "string"
                }
            }
        },
        "models.DeviceResponse": {
            "type": "object",
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "mac_address": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.GetDeviceSensorDataRequest": {
            "type": "object",
            "required": [
                "dateMode",
                "deviceMacId",
                "timestamp"
            ],
            "properties": {
                "dateMode": {
                    "type": "string",
                    "enum": [
                        "hourly",
                        "daily",
                        "weekly",
                        "monthly"
                    ]
                },
                "deviceMacId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.GetDeviceSensorDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SensorData"
                    }
                }
            }
        },
        "models.SensorData": {
            "type": "object",
            "properties": {
                "amperage": {
                    "type": "string"
                },
                "humidity": {
                    "type": "string"
                },
                "temperature": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
