definitions:
  gin.ErrorResponse:
    description: Standard API error response format
    properties:
      message:
        description: Error message
        example: Something went wrong
        type: string
      status:
        description: Always false for errors
        example: false
        type: boolean
    type: object
  gin.Response:
    description: Standard API success response format
    properties:
      data:
        description: Optional data payload
      message:
        description: Optional success message
        example: Operation successful
        type: string
      status:
        description: Indicates success status
        example: true
        type: boolean
    type: object
  models.AddCategoryRequest:
    properties:
      name:
        maxLength: 50
        minLength: 2
        type: string
      type:
        maxLength: 50
        minLength: 2
        type: string
    required:
    - name
    - type
    type: object
  models.AddDeviceRequest:
    properties:
      deviceId:
        maxLength: 50
        minLength: 3
        type: string
      deviceName:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - deviceId
    - deviceName
    type: object
  models.AttachIotPolicyRequest:
    properties:
      identityId:
        type: string
    required:
    - identityId
    type: object
  models.CategoryResponse:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
  models.DeviceResponse:
    properties:
      device_name:
        type: string
      mac_address:
        type: string
      user_id:
        type: string
    type: object
  models.GetDeviceSensorDataRequest:
    properties:
      dateMode:
        enum:
        - hourly
        - daily
        - weekly
        - monthly
        - yearly
        type: string
      deviceMacId:
        type: string
      timestamp:
        type: string
    required:
    - dateMode
    - deviceMacId
    - timestamp
    type: object
  models.GetDeviceSensorDataResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.SensorData'
        type: array
    type: object
  models.SensorData:
    properties:
      amperage:
        type: string
      humidity:
        type: string
      temperature:
        type: string
      timestamp:
        type: integer
    type: object
  models.UserDetails:
    properties:
      city:
        type: string
      country:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      region:
        type: string
      street1:
        type: string
      street2:
        type: string
      zip:
        type: string
    type: object
  models.UserDetailsRequest:
    properties:
      city:
        type: string
      country:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      region:
        type: string
      street1:
        type: string
      street2:
        type: string
      zip:
        type: string
    required:
    - city
    - country
    - email
    - firstName
    - lastName
    - phone
    - region
    - street1
    - zip
    type: object
info:
  contact: {}
paths:
  /category/add:
    post:
      consumes:
      - application/json
      description: Register a new category
      parameters:
      - description: Category information
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.AddCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Category added successfully
          schema:
            $ref: '#/definitions/gin.Response'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "409":
          description: Category already exists
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Add a new category
      tags:
      - Category Management
  /category/all:
    get:
      description: Retrieve all categories
      produces:
      - application/json
      responses:
        "200":
          description: List of categories
          schema:
            items:
              $ref: '#/definitions/models.CategoryResponse'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Get all categories
      tags:
      - Category Management
  /category/type/{type}:
    get:
      consumes:
      - application/json
      description: Retrieve all categories of a specific type
      parameters:
      - description: Category type
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of categories
          schema:
            items:
              $ref: '#/definitions/models.CategoryResponse'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Get categories by type
      tags:
      - Category Management
  /device/add:
    post:
      consumes:
      - application/json
      description: Register a new IoT device for the authenticated user
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Device information
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/models.AddDeviceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Device added successfully
          schema:
            $ref: '#/definitions/gin.Response'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "401":
          description: User not authenticated
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Add a new device
      tags:
      - Device Management
  /device/attach-policy:
    post:
      consumes:
      - application/json
      description: Attach an AWS IoT policy to a Cognito identity
      parameters:
      - description: Identity information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AttachIotPolicyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: IoT policy attached successfully
          schema:
            $ref: '#/definitions/gin.Response'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Failed to attach IoT policy
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Attach IoT policy
      tags:
      - Policy Management
  /device/sensor-data:
    post:
      consumes:
      - application/json
      description: Retrieve sensor data for a specific device with time filtering
      parameters:
      - description: Request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GetDeviceSensorDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sensor data for the device
          schema:
            $ref: '#/definitions/models.GetDeviceSensorDataResponse'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Get device sensor data
      tags:
      - Device Data
  /user/check-parent-id:
    get:
      description: Checks if the authenticated user has a parent ID set in their profile
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns has_parent_id flag
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Error when user ID is not found in context
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error when checking parent ID fails
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check if user has parent ID
  /user/details:
    get:
      description: Retrieves the user details for the authenticated user
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No user details found (null response)
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Error when user is not authenticated
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error when retrieving user details fails
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user details
    post:
      consumes:
      - application/json
      description: Updates or adds user details for the authenticated user
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: User details information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserDetailsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User details updated successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Error when request validation fails
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Error when user is not authenticated
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error when updating user details fails
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update user details
  /user/devices:
    get:
      consumes:
      - application/json
      description: Get all devices registered to the authenticated user
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of user devices
          schema:
            items:
              $ref: '#/definitions/models.DeviceResponse'
            type: array
        "401":
          description: User not authenticated
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user devices
      tags:
      - Device Management
swagger: "2.0"
