definitions:
  gin.ErrorResponse:
    description: Standard API error response format
    properties:
      message:
        description: Error message
        example: Something went wrong
        type: string
      status:
        description: Always false for errors
        example: false
        type: boolean
    type: object
  gin.Response:
    description: Standard API success response format
    properties:
      data:
        description: Optional data payload
      message:
        description: Optional success message
        example: Operation successful
        type: string
      status:
        description: Indicates success status
        example: true
        type: boolean
    type: object
  models.AddDeviceRequest:
    properties:
      deviceId:
        maxLength: 50
        minLength: 3
        type: string
      deviceName:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - deviceId
    - deviceName
    type: object
  models.AttachIotPolicyRequest:
    properties:
      identityId:
        type: string
    required:
    - identityId
    type: object
  models.DeviceResponse:
    properties:
      device_name:
        type: string
      mac_address:
        type: string
      user_id:
        type: string
    type: object
  models.GetDeviceSensorDataRequest:
    properties:
      dateMode:
        enum:
        - hourly
        - daily
        - weekly
        - monthly
        type: string
      deviceMacId:
        type: string
      timestamp:
        type: string
    required:
    - dateMode
    - deviceMacId
    - timestamp
    type: object
  models.GetDeviceSensorDataResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.SensorData'
        type: array
    type: object
  models.SensorData:
    properties:
      amperage:
        type: string
      humidity:
        type: string
      temperature:
        type: string
      timestamp:
        type: integer
    type: object
info:
  contact: {}
paths:
  /device/add:
    post:
      consumes:
      - application/json
      description: Register a new IoT device for the authenticated user
      parameters:
      - description: Device information
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/models.AddDeviceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Device added successfully
          schema:
            $ref: '#/definitions/gin.Response'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "401":
          description: User not authenticated
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Add a new device
      tags:
      - Device Management
  /device/attach-policy:
    post:
      consumes:
      - application/json
      description: Attach an AWS IoT policy to a Cognito identity
      parameters:
      - description: Identity information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AttachIotPolicyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: IoT policy attached successfully
          schema:
            $ref: '#/definitions/gin.Response'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Failed to attach IoT policy
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Attach IoT policy
      tags:
      - Policy Management
  /device/sensor-data:
    post:
      consumes:
      - application/json
      description: Retrieve sensor data for a specific device with time filtering
      parameters:
      - description: Request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GetDeviceSensorDataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sensor data for the device
          schema:
            $ref: '#/definitions/models.GetDeviceSensorDataResponse'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      summary: Get device sensor data
      tags:
      - Device Data
  /user/devices:
    get:
      consumes:
      - application/json
      description: Get all devices registered to the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: List of user devices
          schema:
            items:
              $ref: '#/definitions/models.DeviceResponse'
            type: array
        "401":
          description: User not authenticated
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: List user devices
      tags:
      - Device Management
swagger: "2.0"
