name: Deploy to Staging

on:
  push:
    branches:
      - staging

env:
  IMAGE_NAME: zolaris-go-app
  ECR_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:staging
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > private_key
          chmod 600 private_key
          # ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Staging Server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/app/zolaris-go-backend
            docker-compose -f docker-compose.stage.yml pull
            docker-compose -f docker-compose.stage.yml up -d --build
          EOF

